# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disbug < Formula
  desc "Disbug CLI and MCP server for AI coding agents"
  homepage "https://disbug.io"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.2.0/disbug_0.2.0_darwin_amd64.tar.gz"
      sha256 "6a1ab5101fb77d01bc7cd20caa66177ff19c176e84d5d37c540f4f24ceb6227c"

      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.2.0/disbug_0.2.0_darwin_arm64.tar.gz"
      sha256 "f03db4cb0face5889c7709c9de3d51fa9c4a30042bb004886a5ee07a9d11df0b"

      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.2.0/disbug_0.2.0_linux_amd64.tar.gz"
      sha256 "68ef92f5151ccdc643695faccc0b2c5d4daca160e46b102deab08eee7f8624ba"
      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.2.0/disbug_0.2.0_linux_arm64.tar.gz"
      sha256 "459a8608e6f7804a129bce941d0dcf2b31fdd26c6d7c3243ca0193e45f7279a8"
      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  def caveats
    <<~EOS
      Installation complete. Now use Disbug login to log in.

      Run:
        disbug login
    EOS
  end

  test do
    system "#{bin}/disbug --version"
  end
end
