# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disbug < Formula
  desc "Disbug CLI and MCP server for AI coding agents"
  homepage "https://app.disbug.io"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.4.1/disbug_0.4.1_darwin_amd64.tar.gz"
      sha256 "4b59a99625286989ee3f997d69cd1a90e39b5c41f224a280225a705670ed1873"

      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.4.1/disbug_0.4.1_darwin_arm64.tar.gz"
      sha256 "9e49d45913d1f7d9113408b5f2165c3e864ea906d546f0535a9769b0b32dc1a8"

      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.4.1/disbug_0.4.1_linux_amd64.tar.gz"
      sha256 "6312709cae8c713b184357787f381c0fff7246bdd8c5102c94cf1db54dff9a67"
      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.4.1/disbug_0.4.1_linux_arm64.tar.gz"
      sha256 "c40372f6c3c9ccaa3ac08bc7e4abba7b72fc0828a07266a1532ef58cc6483655"
      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  def caveats
    <<~EOS
      Installation complete. Now run the guided Disbug onboarding flow.

      Run:
        disbug onboard
    EOS
  end

  test do
    system "#{bin}/disbug --version"
  end
end
