# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Disbug < Formula
  desc "Disbug CLI and MCP server for AI coding agents"
  homepage "https://disbug.io"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.3.0/disbug_0.3.0_darwin_amd64.tar.gz"
      sha256 "65881d40565c7dd7d052fb0e60242443c7db4b0c7dca7dd413f02ddbd047658b"

      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.3.0/disbug_0.3.0_darwin_arm64.tar.gz"
      sha256 "c833a34465d4339279ddab2f64a2411609a1f31731a4068f91efba7365e756a5"

      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.3.0/disbug_0.3.0_linux_amd64.tar.gz"
      sha256 "1e6bdc04de2f12ea4d0e08e64b23bf6b19c56eb2dbef900e13f9bc66d9880917"
      define_method(:install) do
        bin.install "disbug"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/disbug-io/disbug-cli/releases/download/v0.3.0/disbug_0.3.0_linux_arm64.tar.gz"
      sha256 "bc8228b5fe7328177f61d5942c3ad7bb93843c7f92c52f33c84762c15f9fd4f8"
      define_method(:install) do
        bin.install "disbug"
      end
    end
  end

  def caveats
    <<~EOS
      Installation complete. Now use Disbug login to log in.

      Run:
        disbug login
    EOS
  end

  test do
    system "#{bin}/disbug --version"
  end
end
